"""Phase 5: Streak badges (~4 badges).

Sets up daily automation for streak badges:
  - 7-Day Login Streak
  - 30-Day Login Streak
  - Submission Streak (7 days)
  - Super Submission Streak (30 days)

Creates a cron job (Linux) or launchd plist (macOS) that:
  1. Makes a Kaggle API call to register a "login" (any API activity counts)
  2. Submits to the Titanic competition daily
"""

import os
import platform
import stat
import sys
from pathlib import Path

from badge_tracker import set_status, should_attempt
from utils import REPO_ROOT, TEMPLATES_DIR, get_kaggle_cli, get_username


DAILY_SCRIPT_PATH = REPO_ROOT / "skills" / "badge-collector" / "scripts" / "daily_streak.sh"
LAUNCHD_PLIST_PATH = Path.home() / "Library" / "LaunchAgents" / "com.kaggle.badge-collector.streak.plist"
CRON_COMMENT = "# kaggle-badge-collector daily streak"


def _create_daily_script() -> Path:
    """Create the daily streak script."""
    kaggle_cli = get_kaggle_cli()
    submission_file = TEMPLATES_DIR / "submission_titanic.csv"

    script = f"""#!/usr/bin/env bash
# Daily Kaggle streak script — auto-generated by badge-collector
# Makes an API call (counts as login) and submits to Titanic

set -euo pipefail

KAGGLE="{kaggle_cli}"

# 1. API activity = login
$KAGGLE datasets list --page-size 1 > /dev/null 2>&1 || true

# 2. Daily Titanic submission (if submission file exists)
SUBMISSION="{submission_file}"
if [ -f "$SUBMISSION" ]; then
    $KAGGLE competitions submit \\
        -c titanic \\
        -f "$SUBMISSION" \\
        -m "Daily streak submission $(date +%Y-%m-%d)" \\
        > /dev/null 2>&1 || true
fi

echo "[$(date)] Streak script completed"
"""
    DAILY_SCRIPT_PATH.write_text(script)
    DAILY_SCRIPT_PATH.chmod(DAILY_SCRIPT_PATH.stat().st_mode | stat.S_IEXEC)
    return DAILY_SCRIPT_PATH


def _setup_launchd() -> bool:
    """Set up macOS launchd plist for daily execution."""
    plist = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.kaggle.badge-collector.streak</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{DAILY_SCRIPT_PATH}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>10</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>{REPO_ROOT}/badge-streak.log</string>
    <key>StandardErrorPath</key>
    <string>{REPO_ROOT}/badge-streak.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>KAGGLE_USERNAME</key>
        <string>{os.getenv('KAGGLE_USERNAME', '')}</string>
        <key>KAGGLE_KEY</key>
        <string>{os.getenv('KAGGLE_KEY', '')}</string>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin</string>
    </dict>
</dict>
</plist>
"""
    LAUNCHD_PLIST_PATH.parent.mkdir(parents=True, exist_ok=True)
    LAUNCHD_PLIST_PATH.write_text(plist)
    print(f"  Created launchd plist: {LAUNCHD_PLIST_PATH}")
    print(f"  To activate: launchctl load {LAUNCHD_PLIST_PATH}")
    print(f"  To deactivate: launchctl unload {LAUNCHD_PLIST_PATH}")
    return True


def _setup_cron() -> bool:
    """Set up cron job for daily execution."""
    import subprocess

    # Check if cron job already exists
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    existing = result.stdout if result.returncode == 0 else ""

    if CRON_COMMENT in existing:
        print("  Cron job already exists")
        return True

    # Add cron job (10:00 AM daily)
    new_cron = existing.rstrip() + f"\n{CRON_COMMENT}\n0 10 * * * {DAILY_SCRIPT_PATH}\n"

    proc = subprocess.run(
        ["crontab", "-"],
        input=new_cron,
        capture_output=True,
        text=True,
    )

    if proc.returncode == 0:
        print("  Cron job installed (runs daily at 10:00 AM)")
        return True
    else:
        print(f"  [WARN] Failed to install cron job: {proc.stderr}")
        return False


def run(username: str) -> tuple[int, int]:
    """Set up daily streak automation. Returns (attempted, succeeded)."""
    badge_ids = [
        "seven_day_login_streak",
        "thirty_day_login_streak",
        "submission_streak",
        "super_submission_streak",
    ]

    actionable = [b for b in badge_ids if should_attempt(b)]
    if not actionable:
        print("  All streak badges already earned/skipped")
        return 0, 0

    print("\n  --- Setting up daily streak automation ---")

    # Create the daily script
    script_path = _create_daily_script()
    print(f"  Created daily script: {script_path}")

    # Set up scheduler based on platform
    system = platform.system()
    if system == "Darwin":
        success = _setup_launchd()
    else:
        success = _setup_cron()

    if success:
        for bid in actionable:
            set_status(bid, "attempting", "daily automation configured — badges earned over time")
        print("\n  Streak automation configured!")
        print("  Badges will be earned after 7/30 days of daily execution.")
        print(f"  Monitor progress: tail -f {REPO_ROOT}/badge-streak.log")
        return len(actionable), len(actionable)
    else:
        for bid in actionable:
            set_status(bid, "failed", "scheduler setup failed")
        print("\n  [FAIL] Could not set up daily automation")
        print(f"  You can manually run: bash {script_path}")
        return len(actionable), 0
